# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ebagis.data.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ebagis_data', '0002_load_pourpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='aoi',
            name='_active',
            field=ebagis.data.models.fields.NullFalseBooleanField(default=True),
        ),
        migrations.AddField(
            model_name='directory',
            name='_active',
            field=ebagis.data.models.fields.NullFalseBooleanField(default=True),
        ),
        migrations.AddField(
            model_name='file',
            name='_active',
            field=ebagis.data.models.fields.NullFalseBooleanField(default=True),
        ),
        migrations.AddField(
            model_name='filedata',
            name='_active',
            field=ebagis.data.models.fields.NullFalseBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='aoi',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aoi',
            name='pourpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='_aois', to='ebagis_data.PourPoint'),
        ),
        migrations.AlterField(
            model_name='directory',
            name='_parent_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_subdirectories', to='ebagis_data.Directory'),
        ),
        migrations.AlterField(
            model_name='file',
            name='_parent_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_files', to='ebagis_data.Directory'),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='_parent_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_versions', to='ebagis_data.File'),
        ),
        migrations.AlterUniqueTogether(
            name='aoi',
            unique_together=set([('name', '_active')]),
        ),
        migrations.AlterUniqueTogether(
            name='directory',
            unique_together=set([('_parent_object', 'name', '_active')]),
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together=set([('_parent_object', 'name', '_active')]),
        ),
    ]
