# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 03:26
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import drf_chunked_upload.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('djcelery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AOI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('shortname', models.CharField(max_length=25)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('classname', models.CharField(max_length=40)),
                ('archiving_rule', models.CharField(choices=[(b'NONE', b'No Archiving'), (b'INDIVIDUAL', b'Individual Archiving'), (b'GROUP', b'Group Archiving'), (b'READONLY', b'Read Only (No Archiving)')], default=b'NONE', editable=False, max_length=10)),
                ('_parent_directory', models.CharField(max_length=1000)),
                ('_parent_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdirectories', to='ebagis.Directory')),
                ('aoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directory', to='ebagis.AOI')),
            ],
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to=b'')),
                ('querydate', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='download', to='djcelery.TaskMeta')),
            ],
            options={
                'abstract': False,
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='ExpiringToken',
            fields=[
                ('key', models.CharField(max_length=40, unique=True, verbose_name='Key')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='token', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('classname', models.CharField(max_length=40)),
                ('_parent_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='ebagis.Directory')),
                ('aoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='ebagis.AOI')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ebagis_file_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('classname', models.CharField(max_length=40)),
                ('encoding', models.CharField(blank=True, max_length=20, null=True)),
                ('sha256', models.CharField(max_length=64)),
                ('_parent_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='ebagis.File')),
                ('aoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filedata', to='ebagis.AOI')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ebagis_filedata_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PourPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, null=True, srid=4326)),
                ('awdb_id', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=255, upload_to=drf_chunked_upload.models.generate_filename)),
                ('filename', models.CharField(max_length=255)),
                ('offset', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, b'Incomplete'), (2, b'Complete')], default=1)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('is_update', models.BooleanField(default=False)),
                ('parent_object_id', models.UUIDField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('parent_object_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload_parent', to='contenttypes.ContentType')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload', to='djcelery.TaskMeta')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='upload', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='download',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='download', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ebagis_directory_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aoi',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ebagis_aoi_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aoi',
            name='parent_aoi',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_aois', to='ebagis.AOI'),
        ),
        migrations.AddField(
            model_name='aoi',
            name='pourpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aois', to='ebagis.PourPoint'),
        ),
        migrations.CreateModel(
            name='AOIDirectory',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('ebagis.directory',),
        ),
        migrations.CreateModel(
            name='Geodatabase',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('ebagis.directory',),
        ),
        migrations.CreateModel(
            name='HRUZones',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('ebagis.directory',),
        ),
        migrations.CreateModel(
            name='HRUZonesData',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('ebagis.directory',),
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('ebagis.file',),
        ),
        migrations.CreateModel(
            name='LayerData',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('ebagis.filedata',),
        ),
        migrations.CreateModel(
            name='Maps',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('ebagis.directory',),
        ),
        migrations.CreateModel(
            name='PrismDir',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('ebagis.directory',),
        ),
        migrations.CreateModel(
            name='Zones',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('ebagis.directory',),
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together=set([('_parent_object', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='directory',
            unique_together=set([('_parent_object', 'name')]),
        ),
        migrations.CreateModel(
            name='Geodatabase_GroupArchive',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('ebagis.geodatabase',),
        ),
        migrations.CreateModel(
            name='Geodatabase_IndividualArchive',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('ebagis.geodatabase',),
        ),
        migrations.CreateModel(
            name='Geodatabase_ReadOnly',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('ebagis.geodatabase',),
        ),
        migrations.CreateModel(
            name='Raster',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('ebagis.layer',),
        ),
        migrations.CreateModel(
            name='RasterData',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('ebagis.layerdata',),
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('ebagis.layer',),
        ),
        migrations.CreateModel(
            name='TableData',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('ebagis.layerdata',),
        ),
        migrations.CreateModel(
            name='Vector',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('ebagis.layer',),
        ),
        migrations.CreateModel(
            name='VectorData',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('ebagis.layerdata',),
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('ebagis.geodatabase_individualarchive',),
        ),
        migrations.CreateModel(
            name='AOIdb',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('ebagis.geodatabase_readonly',),
        ),
        migrations.CreateModel(
            name='HRUZonesGDB',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('ebagis.geodatabase_readonly',),
        ),
        migrations.CreateModel(
            name='Layers',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('ebagis.geodatabase_individualarchive',),
        ),
        migrations.CreateModel(
            name='ParamGDB',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('ebagis.geodatabase_readonly',),
        ),
        migrations.CreateModel(
            name='Prism',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('ebagis.geodatabase_grouparchive',),
        ),
        migrations.CreateModel(
            name='Surfaces',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('ebagis.geodatabase_readonly',),
        ),
    ]
