# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-21 03:03
# edited to add data loading
from __future__ import unicode_literals

from django.db import migrations


def load_pourpoints_from_fixture(apps, schema_editor):
    from django.core.management import call_command
    call_command("loaddata", "pourpoints")


class Migration(migrations.Migration):

    dependencies = [
        ('ebagis', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_pourpoints_from_fixture),
    ]
