# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-05 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebagis', '0002_auto_20160316_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload', to='djcelery.TaskMeta'),
        ),
    ]
