# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebagis', '0004_auto_20160410_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hruzonesdata',
            name='paramgdb',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hru_zones_params', to='ebagis.ParamGDB'),
        ),
    ]
