# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-21 03:03
# edited to add pourpoint loading and AOI/pourpoint matching
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
from ebagis.settings import GEO_WKID


def load_pourpoints_from_fixture(apps, schema_editor):
    from django.core.management import call_command
    call_command("loaddata", "pourpoints")


def add_pourpoints_to_aois(apps, schema_editor):
    from ebagis.utils import gis

    AOI = apps.get_model('ebagis', 'AOI')
    File = apps.get_model('ebagis', 'File')
    PourPoint = apps.get_model('ebaigs', 'PourPoint')

    for aoi in AOI.objects.all():
        # get the path to the pourpoint shapefile on disk
        fc = File.objects.filter(
            name="pourpoint", aoi_id=aoi.id
        )[0].versions.get().path
        # get the WKT for the pourpoint and reporject to the specified CRS
        wkt = gis.get_wkt_geometry_and_reproject(fc+".shp", GEO_WKID)
        # match the AOI to the respective PourPoint record
        aoi.pourpoint = PourPoint.match(wkt, aoi.boundary, aoi_name=aoi.name)
        aoi.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ebagis', '0005_auto_20160820_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='PourPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=GEO_WKID)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, null=True, srid=GEO_WKID)),
                ('awdb_id', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='aoi',
            name='pourpoint',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='aois',
                to='ebagis.PourPoint',
            ),
        ),
        migrations.AlterField(
            model_name='aoi',
            name='boundary',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                geography=True,
                srid=4326
            ),
        ),
        migrations.RunPython(load_pourpoints_from_fixture),
        migrations.RunPython(add_pourpoints_to_aois),
        # we have filled in the PourPoint relations so we can
        # make the PourPoint foreign key a required field now
        migrations.AlterField(
            model_name='aoi',
            name='pourpoint',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='aois',
                to='ebagis.PourPoint',
            ),
        ),
    ]
