# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-21 03:03
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebagis', '0005_auto_20160820_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='PourPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('awdb_id', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='aoi',
            name='pourpoint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ebagis.PourPoint'),
        ),
    ]
