# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 02:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebagis', '0007_auto_20170304_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='TXT',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('ebagis.file',),
        ),
        migrations.CreateModel(
            name='TXTData',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('ebagis.filedata',),
        ),
    ]
